npm:
  publish: false
hooks:
  after:bump:
    - rm -f zips/tinder-autopilot-v*.zip
    - bash chrome/bump-version.sh ${version}
    - yarn build
    - cd zips/ && bestzip tinder-autopilot-v${version}.zip * && cd ..
  after:release: rm zips/tinder-autopilot-v*.zip
git:
  requireCleanWorkingDir: false
github:
  assets:
    - zips/tinder-autopilot-v*.zip
  release: true
